### ISSUE TITLE
Ghost Submissions

### ISSUE THREAD

**Issue by mliyanagamage** [frankzhao/SubmissionApp2#2]
After adding and compiling a submission successfully, deleting said submission leaves the submission intact without the files. 

![image](https://cloud.githubusercontent.com/assets/7357299/9103496/2606fe60-3c42-11e5-8d41-92738522562c.png)

**Comment by mliyanagamage** [comment]
Further information, doing a second delete on the submission, totally deleted it from my user account, can no longer see it.

**Comment by frankzhao** [comment]
It is possible that this occurs when you try to view a submission during the deletion transaction. Regardless, I can't reproduce this and I don't think it's a bug. Please reopen if it occurs again.
